### PR TITLE
bugfix download not working with course codes

### PR DESCRIPTION
**Pull request by prnvbn**

### CODE REVIEW

**Comment by Akshat-Tripathi** [comment]
Doesn't this just switch over to using course codes rather than names?

**Comment by prnvbn** [comment]
@Akshat-Tripathi that's what it is meant for no? Check the last line in the README - https://github.com/goDoCer/scientiaCLI#how-to-use

**Comment by Akshat-Tripathi** [comment]
> @Akshat-Tripathi that's what it is meant for no? Check the last line in the README - https://github.com/goDoCer/scientiaCLI#how-to-use

Yeah

**Review by Akshat-Tripathi — APPROVED** [review]
lgtm

**Pull request merged**
